name: Merging & Locking

on:
  issue_comment:

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  squash_merge:
    runs-on: ubuntu-latest
    if: >-
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/merge') &&
      github.event.comment.user.id == 2387514
    steps:
      - run: echo "${{ toJSON(github.event.issue.title) }}"
#       - name: Squash & Merge
#         run: gh pr merge ${{ env.ISSUE }} -t "${{ env.COMMENT }}"
#         working-directory: ${{ github.workspace }}
#         env:
#           ISSUE: ${{ github.event.pull_request.html_url }}
#           SQUASH_TITLE: "(#${{ github.event.number}}) "
